### ISSUE TITLE
Add Windows Releases.

### ISSUE THREAD

**Issue by ghost** [Everest187/Artemis-Sniper#1]
Add .exe Releases for Windows Users using PyInstaller.

**Comment by TheRedstoneRadiant** [comment]
IM GETTING TO IT OK

**Comment by Everest187** [comment]
Tbh when exiting it'll close the window immediately once the requests are over and I don't want "press enter to exit" all over my code so..

**Comment by TheRedstoneRadiant** [comment]
You could put one on the last line

**Comment by ghost** [comment]
Run Artemis from another script, which would close after Artemis

**Comment by Everest187** [comment]
Smart! I'll get to it in a few mins

**Comment by ghost** [comment]
> Run Artemis from another script, which would close after Artemis

yep.

**Comment by ghost** [comment]
This has still not been addressed.

**Comment by ghost** [comment]
@Everest187 DO IT

**Comment by ghost** [comment]
Dude when will this even ***ever*** be addressed

**Comment by ghost** [comment]
Should i close this? As run.bat and run.py exist now?

**Comment by ghost** [comment]
Those are for updating artemis, I presume
